CREATE TABLE [dbo].[Game]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [RedPlayerID] UNIQUEIDENTIFIER NOT NULL, 
    [YellowPlayerID] UNIQUEIDENTIFIER NOT NULL, 
    [State] NVARCHAR(MAX) NOT NULL
)
