CREATE TABLE [dbo].[Game]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [RedPlayerID] UNIQUEIDENTIFIER NOT NULL, 
    [YellowPlayerID] UNIQUEIDENTIFIER NOT NULL, 
    [State] NVARCHAR(MAX) NOT NULL,
CONSTRAINT ak_Game UNIQUE (RedPlayerID, YellowPlayerID),
CONSTRAINT ak_Game_Red FOREIGN KEY (RedPlayerID) REFERENCES dbo.Players,
CONSTRAINT ak_Game_Yellow FOREIGN KEY (YellowPlayerID) REFERENCES dbo.Players
)
