CREATE TABLE [dbo].[Players]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [TeamName] NVARCHAR(100) NOT NULL,
    [Password] NVARCHAR(100) NOT NULL, 
    [SystemBot] BIT NOT NULL DEFAULT 0,
CONSTRAINT ak_Players UNIQUE (TeamName)
)
